workspace:
  path: static-hoster
  base: /build


pipeline:
  build:
    image: docker:23-cli
    privileged: true
    commands:
      - docker buildx build --no-cache -t dev.cat-enby.club/nikurasu/static-hoster:latest -t dev.cat-enby.club/nikurasu/static-hoster:v$CI_COMMIT_TAG -f dev/docker/images/production/Dockerfile .
      - docker login -u $USER -p $PASSWORD dev.cat-enby.club
      - docker push dev.cat-enby.club/nikurasu/static-hoster:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: tag
    secrets: [ user, password ]

branches: main
